AllCops:
  NewCops: enable

require:
  - rubocop

Style/YodaCondition:
  EnforcedStyle: require_for_all_comparison_operators

Style/NumericPredicate:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Metrics/AbcSize:
  Max: 70

Metrics/CyclomaticComplexity:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 25

Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 115